# !/opt/conda/bin/python3
# -*- coding: utf-8 -*-
MAX_LENGTH=128
MAX_SST_LENGTH = 128
MAX_AG_LENGTH = 256
MAX_IMDB_LENGTH = 512
MAX_BOOKCORPUS_LENGTH = 64
MAX_EVAL_LENGTH = 510

GENERATE_MIN_LENGTH = 40
GENERATE_MAX_LENGTH = 60
GENERATE_TOPK = 10
GENERATE_REPITATION_PALNITY = 1.2
GENERATE_NO_REPEAT_NGRAM_SIZE = 3
GPT2_PAD_TOKEN = '<|endoftext|>'
CTRL_PAD_TOKEN = '<unk>'
GPT2_PAD_TOKEN_ID = 50256
CTRL_PAD_TOKEN_ID = 246532

GPT2_END_OF_SENT = 13
